#!/usr/bin/env node
/**
 * Provision synthetic Firebase Auth identities for authenticated Playwright UAT.
 * Writes passwords to docs/reports/evidence/uat_tokens.env (gitignored).
 * Prefers email/password (ADC can set passwords). Custom tokens optional if SA signing available.
 * Does not print secret values. Requires ADC for project servesa-aad53.
 */
'use strict'

const fs = require('fs')
const path = require('path')
const crypto = require('crypto')
const admin = require('firebase-admin')

const PROJECT = 'servesa-aad53'
const OUT = path.resolve(
  __dirname,
  '../../docs/reports/evidence/uat_tokens.env'
)
const META_OUT = path.resolve(
  __dirname,
  '../../docs/reports/evidence/uat_identities_meta.json'
)

const IDENTITIES = [
  {
    key: 'CITIZEN',
    email: 'uat.citizen.pilot@servesa.test',
    displayName: 'UAT Citizen Pilot',
    claims: {},
  },
  {
    key: 'OFFICIAL',
    email: 'uat.official.jhb.pilot@servesa.test',
    displayName: 'UAT Official JHB',
    claims: {
      roles: ['official'],
      municipalityCode: 'JHB',
      departmentId: 'roads',
    },
  },
  {
    key: 'ADMIN',
    email: 'uat.admin.jhb.pilot@servesa.test',
    displayName: 'UAT Admin JHB',
    claims: {
      roles: ['official', 'admin'],
      municipalityCode: 'JHB',
      departmentId: 'roads',
    },
  },
  {
    key: 'SUPERVISOR',
    email: 'uat.supervisor.jhb.pilot@servesa.test',
    displayName: 'UAT Supervisor JHB',
    claims: {
      roles: ['official', 'moderator'],
      municipalityCode: 'JHB',
      departmentId: 'roads',
    },
  },
  {
    key: 'FIELD',
    email: 'uat.field.jhb.pilot@servesa.test',
    displayName: 'UAT Field JHB',
    claims: {
      roles: ['field_worker'],
      municipalityCode: 'JHB',
      departmentId: 'roads',
    },
  },
  {
    key: 'OFFICIAL_CPT',
    email: 'uat.official.cpt.pilot@servesa.test',
    displayName: 'UAT Official CPT',
    claims: {
      roles: ['official'],
      municipalityCode: 'CPT',
      departmentId: 'roads',
    },
  },
  {
    key: 'SUSPENDED',
    email: 'uat.suspended.pilot@servesa.test',
    displayName: 'UAT Suspended Pilot',
    claims: {
      roles: ['official'],
      municipalityCode: 'JHB',
    },
    disabled: true,
  },
]

function passwordFor(key) {
  // Deterministic per-machine? No — random each provision; stored only in gitignored env.
  return `UatPilot!${key}!${crypto.randomBytes(12).toString('base64url')}`
}

async function ensureUser(spec, password) {
  const auth = admin.auth()
  let user
  try {
    user = await auth.getUserByEmail(spec.email)
    user = await auth.updateUser(user.uid, {
      password,
      displayName: spec.displayName,
      emailVerified: true,
      disabled: Boolean(spec.disabled),
    })
  } catch (e) {
    if (e.code !== 'auth/user-not-found') throw e
    user = await auth.createUser({
      email: spec.email,
      emailVerified: true,
      displayName: spec.displayName,
      disabled: Boolean(spec.disabled),
      password,
    })
  }
  if (spec.claims && Object.keys(spec.claims).length > 0) {
    await auth.setCustomUserClaims(user.uid, spec.claims)
  } else {
    await auth.setCustomUserClaims(user.uid, null)
  }
  const db = admin.firestore()
  await db
    .collection('users')
    .doc(user.uid)
    .set(
      {
        email: spec.email,
        displayName: spec.displayName,
        roles: spec.claims.roles || [],
        municipalityCode: spec.claims.municipalityCode || null,
        municipalityId: spec.claims.municipalityCode || null,
        departmentId: spec.claims.departmentId || null,
        role: (spec.claims.roles || []).includes('field_worker')
          ? 'field_worker'
          : (spec.claims.roles || []).includes('official')
            ? 'official'
            : 'citizen',
        syntheticUat: true,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      },
      { merge: true }
    )
  let customToken = null
  try {
    customToken = await auth.createCustomToken(user.uid, spec.claims || {})
  } catch {
    customToken = null
  }
  return {
    uid: user.uid,
    email: spec.email,
    key: spec.key,
    disabled: Boolean(spec.disabled),
    password,
    customToken,
  }
}

async function main() {
  if (!admin.apps.length) {
    admin.initializeApp({ projectId: PROJECT })
  }
  const results = []
  for (const spec of IDENTITIES) {
    results.push(await ensureUser(spec, passwordFor(spec.key)))
  }
  const envLines = [
    '# Generated by tools/pilot/provision_uat_identities.js — DO NOT COMMIT',
    `# project=${PROJECT}`,
    `# generated_utc=${new Date().toISOString()}`,
    '# Auth mode: email/password (PILOT_UAT_*_EMAIL / PILOT_UAT_*_PASSWORD)',
    '# Optional custom tokens present only if SA signing succeeded',
  ]
  for (const r of results) {
    const prefix =
      r.key === 'OFFICIAL_CPT'
        ? 'PILOT_UAT_OFFICIAL_CPT'
        : `PILOT_UAT_${r.key}`
    envLines.push(`${prefix}_EMAIL=${r.email}`)
    envLines.push(`${prefix}_PASSWORD=${r.password}`)
    // Back-compat: TOKEN env carries "email\\npassword" JSON for Playwright helper
    const payload = Buffer.from(
      JSON.stringify({ email: r.email, password: r.password, mode: 'password' }),
      'utf8'
    ).toString('base64url')
    envLines.push(`${prefix}_TOKEN=${payload}`)
    if (r.customToken) {
      envLines.push(`${prefix}_CUSTOM_TOKEN=${r.customToken}`)
    }
  }
  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, envLines.join('\n') + '\n', { mode: 0o600 })
  const meta = {
    project: PROJECT,
    generated_utc: new Date().toISOString(),
    auth_mode: 'email_password',
    custom_tokens_available: results.every((r) => Boolean(r.customToken)),
    identities: results.map(({ uid, email, key, disabled }) => ({
      uid,
      email,
      key,
      disabled,
    })),
    token_file: 'docs/reports/evidence/uat_tokens.env',
    note: 'Passwords in uat_tokens.env only; never commit.',
  }
  fs.writeFileSync(META_OUT, JSON.stringify(meta, null, 2) + '\n')
  console.log(
    JSON.stringify(
      {
        provisioned: results.length,
        meta: META_OUT,
        token_file_written: true,
        custom_tokens: results.filter((r) => r.customToken).length,
        emails: results.map((r) => r.email),
      },
      null,
      2
    )
  )
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
